import type { Metadata } from "next";
import "./globals.css";
import { Providers } from "./providers"; // Import Providers

export const metadata: Metadata = {
  title: "Secure Vault",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body>
        <Providers>{children}</Providers> {/* Wrap children */}
      </body>
    </html>
  );
}